# change the followings to match your Github username and repo name
baseurl: "/tailwind" # the name of your github repo
url: "https://raulgarciawk.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Tailpages: Tailwind + Github Pages"
description: A Github Pages (Jekyll) template based on TailwindCSS

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Raul Garcia
author-bio: false # change to false to hide
author-image: 279.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Pop
  permalink: pop
- text: Blog
  permalink: blog
- text: Cards
  permalink: cards.html

# use false to turn off any social media links
twitter: https://twitter.com/
facebook: https://facebook.com/
instagram: https://instagram.com/
github: https://github.com/
linkedin: https://linkedin.com/
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Powered by Tailpages"

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
